<a href="https://colab.research.google.com/github/Akhil-2001/Recurrance_Prediction/blob/main/RecPred_LR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
col_names=['id', 'outcome', 'time', 'radius_mean',	'texture_mean',	'perimeter_mean',	'area_mean',	'smoothness_mean',	'compactness_mean',	'concavity_mean',	'concave_points_mean',	'symmetry_mean', 'fractal_dimension_mean', 'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se', 'compactness_se', 'concavity_se', 'concave_points_se', 'symmetry_se', 'fractal_dimension_se', 'radius_worst', 'texture_worst',	'perimeter_worst',	'area_worst',	'smoothness_worst', 'compactness_worst',	'concavity_worst',	'concave_points_worst',	'symmetry_worst',	'fractal_dimension_worst', 'tumor_size', 'lymph_node_status'	]

In [ ]:
len(col_names)

35

In [ ]:
COLUMNS_COUNT = 36


# with open(fl.data, 'r') as f:
#     columns = [next(f).strip() for line in range(COLUMNS_COUNT)]

temp_df = pd.read_csv('https://raw.githubusercontent.com/Akhil-2001/Recurrance_Prediction/main/wpbc.data', skiprows=COLUMNS_COUNT, header=None, delimiter=',', skip_blank_lines=False)

temp_df

0  1    2      3      4       5       6        7        8        9   \
0    856385  N   76  13.17  21.81   85.42   531.5  0.09714  0.10470  0.08259   
1    857010  R    8  18.65  17.60  123.70  1076.0  0.10990  0.16860  0.19740   
2     85715  N  111  13.17  18.66   85.98   534.6  0.11580  0.12310  0.12260   
3    857438  R   48  15.10  22.02   97.26   712.8  0.09056  0.07081  0.05253   
4    857637  R   11  19.21  18.57  125.50  1152.0  0.10530  0.12670  0.13230   
..      ... ..  ...    ...    ...     ...     ...      ...      ...      ...   
157  942640  N   10  22.52  21.92  146.90  1597.0  0.07592  0.09162  0.06862   
158  943471  N    8  15.44  31.18  101.00   740.4  0.09399  0.10620  0.13750   
159   94547  N   12  17.17  29.19  110.00   915.3  0.08952  0.06655  0.06583   
160  947204  R    3  21.42  22.84  145.00  1440.0  0.10700  0.19390  0.23800   
161  947489  N    6  16.70  28.13  110.30   885.4  0.08896  0.11310  0.10120   

     ...     25      26       27      28      29       30      31       32  \
0    ...  105.5   740.7  0.15030  0.3904  0.3728  0.16070  0.3693  0.09618   
1    ...  150.6  1567.0  0.16790  0.5090  0.7345  0.23780  0.3799  0.09185   
2    ...  102.8   759.4  0.17860  0.4166  0.5006  0.20880  0.3900  0.11790   
3    ...  117.7  1030.0  0.13890  0.2057  0.2712  0.15300  0.2675  0.07873   
4    ...  170.1  2145.0  0.16240  0.3511  0.3879  0.20910  0.3537  0.08294   
..   ...    ...     ...      ...     ...     ...      ...     ...      ...   
157  ...  162.1  1902.0  0.08191  0.1319  0.1056  0.09378  0.2061  0.05788   
158  ...  112.6   929.0  0.12720  0.2362  0.2975  0.12860  0.2914  0.08024   
159  ...  132.5  1295.0  0.12610  0.1572  0.2141  0.09520  0.3362  0.06033   
160  ...  198.3  2375.0  0.14980  0.4379  0.5411  0.22150  0.2832  0.08981   
161  ...  128.8  1213.0  0.13300  0.2808  0.3455  0.13170  0.3035  0.08036   

      33  34  
0    1.7   1  
1    1.8   0  
2    1.0   1  
3    2.5   0  
4    3.2  13  
..   ...  ..  
157  6.0   2  
158  1.5   0  
159  3.7   0  
160  3.0   ?  
161  3.5   0  

[162 rows x 35 columns]

In [ ]:
temp_df.columns=col_names

In [ ]:
temp_df.head()

id outcome  time  radius_mean  texture_mean  perimeter_mean  area_mean  \
0  856385       N    76        13.17         21.81           85.42      531.5   
1  857010       R     8        18.65         17.60          123.70     1076.0   
2   85715       N   111        13.17         18.66           85.98      534.6   
3  857438       R    48        15.10         22.02           97.26      712.8   
4  857637       R    11        19.21         18.57          125.50     1152.0   

   smoothness_mean  compactness_mean  concavity_mean  ...  perimeter_worst  \
0          0.09714           0.10470         0.08259  ...            105.5   
1          0.10990           0.16860         0.19740  ...            150.6   
2          0.11580           0.12310         0.12260  ...            102.8   
3          0.09056           0.07081         0.05253  ...            117.7   
4          0.10530           0.12670         0.13230  ...            170.1   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0       740.7            0.1503             0.3904           0.3728   
1      1567.0            0.1679             0.5090           0.7345   
2       759.4            0.1786             0.4166           0.5006   
3      1030.0            0.1389             0.2057           0.2712   
4      2145.0            0.1624             0.3511           0.3879   

   concave_points_worst  symmetry_worst  fractal_dimension_worst  tumor_size  \
0                0.1607          0.3693                  0.09618         1.7   
1                0.2378          0.3799                  0.09185         1.8   
2                0.2088          0.3900                  0.11790         1.0   
3                0.1530          0.2675                  0.07873         2.5   
4                0.2091          0.3537                  0.08294         3.2   

   lymph_node_status  
0                  1  
1                  0  
2                  1  
3                  0  
4                 13  

[5 rows x 35 columns]

In [ ]:
temp_df.isna().sum()

id                         0
outcome                    0
time                       0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave_points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave_points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave_points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
tumor_size                 0
lymph_node_sta

In [ ]:
df = temp_df

In [ ]:
df['outcome'].value_counts()

N    122
R     40
Name: outcome, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder,StandardScaler
df['lymph_node_status'] = LabelEncoder().fit_transform(df['lymph_node_status'].values)

In [ ]:
X = df.iloc[:,2:].values
y = df.iloc[:,1].values

In [ ]:
labelencode = LabelEncoder()
y=labelencode.fit_transform(y)
print("Reccur: ",(y == 1).sum())

Reccur:  40


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=5)
print("Reccur: ",(y_train == 1).sum())

Reccur:  28


# Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.svm import SVC

model = make_pipeline(StandardScaler(), LogisticRegression())
model.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression())])

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, f1_score

y_pred = model.predict(X_test)

print("accuracy: ",accuracy_score(y_test,y_pred))
print("F1_score: ",f1_score(y_test,y_pred))
print("Recall: ",recall_score(y_test,y_pred))

accuracy:  0.7575757575757576
F1_score:  0.6
Recall:  0.5


In [ ]:
confusion_matrix(y_test,y_pred)

array([[19,  2],
       [ 6,  6]])

In [ ]:
from sklearn.preprocessing import LabelEncoder,StandardScaler
df['outcome'] = LabelEncoder().fit_transform(df['outcome'].values)

In [ ]:
df.head()

id  outcome  time  radius_mean  texture_mean  perimeter_mean  \
0  856385        0    76        13.17         21.81           85.42   
1  857010        1     8        18.65         17.60          123.70   
2   85715        0   111        13.17         18.66           85.98   
3  857438        1    48        15.10         22.02           97.26   
4  857637        1    11        19.21         18.57          125.50   

   area_mean  smoothness_mean  compactness_mean  concavity_mean  ...  \
0      531.5          0.09714           0.10470         0.08259  ...   
1     1076.0          0.10990           0.16860         0.19740  ...   
2      534.6          0.11580           0.12310         0.12260  ...   
3      712.8          0.09056           0.07081         0.05253  ...   
4     1152.0          0.10530           0.12670         0.13230  ...   

   perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0            105.5       740.7            0.1503             0.3904   
1            150.6      1567.0            0.1679             0.5090   
2            102.8       759.4            0.1786             0.4166   
3            117.7      1030.0            0.1389             0.2057   
4            170.1      2145.0            0.1624             0.3511   

   concavity_worst  concave_points_worst  symmetry_worst  \
0           0.3728                0.1607          0.3693   
1           0.7345                0.2378          0.3799   
2           0.5006                0.2088          0.3900   
3           0.2712                0.1530          0.2675   
4           0.3879                0.2091          0.3537   

   fractal_dimension_worst  tumor_size  lymph_node_status  
0                  0.09618         1.7                  1  
1                  0.09185         1.8                  0  
2                  0.11790         1.0                  1  
3                  0.07873         2.5                  0  
4                  0.08294         3.2                  3  

[5 rows x 35 columns]

In [ ]:
from scipy.stats import pointbiserialr

In [ ]:
Dict={}

In [ ]:
mask = df['outcome'] == 1
df1 = df[mask]
df1 = df1.iloc[:,2:]
df2 = df[~mask]

In [ ]:
df1.head()

time  radius_mean  texture_mean  perimeter_mean  area_mean  \
1     8        18.65         17.60          123.70     1076.0   
3    48        15.10         22.02           97.26      712.8   
4    11        19.21         18.57          125.50     1152.0   
6    34        14.25         22.15           96.42      645.7   
7    19        12.68         23.84           82.69      499.0   

   smoothness_mean  compactness_mean  concavity_mean  concave_points_mean  \
1          0.10990           0.16860         0.19740              0.10090   
3          0.09056           0.07081         0.05253              0.03334   
4          0.10530           0.12670         0.13230              0.08994   
6          0.10490           0.20080         0.21350              0.08653   
7          0.11220           0.12620         0.11280              0.06873   

   symmetry_mean  ...  perimeter_worst  area_worst  smoothness_worst  \
1         0.1907  ...            150.6      1567.0            0.1679   
3         0.1616  ...            117.7      1030.0            0.1389   
4         0.1917  ...            170.1      2145.0            0.1624   
6         0.1949  ...            119.1       959.5            0.1640   
7         0.1905  ...            111.8       888.3            0.1851   

   compactness_worst  concavity_worst  concave_points_worst  symmetry_worst  \
1             0.5090           0.7345                0.2378          0.3799   
3             0.2057           0.2712                0.1530          0.2675   
4             0.3511           0.3879                0.2091          0.3537   
6             0.6247           0.6922                0.1785          0.2844   
7             0.4061           0.4024                0.1716          0.3383   

   fractal_dimension_worst  tumor_size  lymph_node_status  
1                  0.09185         1.8                  0  
3                  0.07873         2.5                  0  
4                  0.08294         3.2                  3  
6                  0.11320         1.5                  0  
7                  0.10310         1.2                  1  

[5 rows x 33 columns]

In [ ]:
for i in col_names:
  Dict[i]=pointbiserialr(df['outcome'], df[i]).correlation
  print(i+":"+str(pointbiserialr(df['outcome'], df[i]).correlation))

id:-0.03836062374039954
outcome:0.9999999999999998
time:-0.3348579690029069
radius_mean:0.1656544697345868
texture_mean:-0.09132548705754732
perimeter_mean:0.1659429183426265
area_mean:0.18272267142822507
smoothness_mean:0.00497594291017075
compactness_mean:-0.021726167983664068
concavity_mean:0.038147813211818066
concave_points_mean:0.10796510624529504
symmetry_mean:-0.13790659409866948
fractal_dimension_mean:-0.1479866922162997
radius_se:0.12450267336929242
texture_se:-0.1026850248585221
perimeter_se:0.12812654454125028
area_se:0.14854958369174406
smoothness_se:-0.09523940924755786
compactness_se:-0.04396573869321829
concavity_se:-0.11130026300884971
concave_points_se:-0.10991843936976267
symmetry_se:-0.05674010723415575
fractal_dimension_se:-0.0829244466711495
radius_worst:0.23649268523607034
texture_worst:-0.07278413166482885
perimeter_worst:0.23166864088800476
area_worst:0.23930337451994332
smoothness_worst:0.026548552201030525
compactness_worst:-0.01912177837422572
concavity_wors

In [ ]:
# import operator
# sorted = sorted(Dict, key=Dict.get)

In [ ]:
# print(sorted)

In [ ]:
# train=df.sample(frac=0.8,random_state=200) #random state is a seed value
# test=df.drop(train.index)

# Logistic Regression with Correlations

In [ ]:
from sklearn import linear_model
mlr = linear_model.LogisticRegression()

X=df[['time', 'fractal_dimension_mean', 'area_worst', 'lymph_node_status']].values
y=df['outcome'].values

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=5)




In [ ]:
mlr.fit(X_train, y_train)
#print(mlr.coef_)

LogisticRegression()

In [ ]:
pred_y = mlr.predict(X_test)
m = pred_y.mean()
# for i in range(len(pred_y)):
#   if pred_y[i] >= m:
#     pred_y[i] = 1
#   else:
#     pred_y[i] = 0

print("Accuracy",accuracy_score(y_test, pred_y))
print("F1_score",f1_score(y_test, pred_y))
print("Recall",recall_score(y_test, pred_y))

Accuracy 0.8787878787878788
F1_score 0.8
Recall 0.6666666666666666


# Time Linear Regression

In [ ]:
Dict2=dict()
correlation = df1.corr()
col_names2 = col_names[2:]
for i in col_names2:
  Dict2[i]=correlation.loc['time', i]
  print(i+":"+str(correlation.loc['time', i]))

time:1.0
radius_mean:-0.3749259024573016
texture_mean:0.014395189972563414
perimeter_mean:-0.37636997492008706
area_mean:-0.35817591363011586
smoothness_mean:0.05335697657346742
compactness_mean:-0.20352376008692796
concavity_mean:-0.27794916272927545
concave_points_mean:-0.318120303442199
symmetry_mean:0.1826539044730002
fractal_dimension_mean:0.16128543993520786
radius_se:-0.1446823819565408
texture_se:0.25933091848955186
perimeter_se:-0.12068581088326055
area_se:-0.19771041431426892
smoothness_se:0.034121080120362225
compactness_se:0.04252424756549347
concavity_se:-0.08428719108617608
concave_points_se:-0.046294240186226764
symmetry_se:0.00800770009457895
fractal_dimension_se:0.15070210660335367
radius_worst:-0.3595859180251384
texture_worst:0.13787185550737124
perimeter_worst:-0.3535535810462717
area_worst:-0.33309683377279126
smoothness_worst:0.05024808661802566
compactness_worst:-0.073584730001135
concavity_worst:-0.19521571561008402
concave_points_worst:-0.3405416297326542
symme

In [ ]:
Dict2 = [(k, v) for k, v in Dict2.items()]

In [ ]:
Dict2.sort(key=lambda x: x[1])

In [ ]:
Dict2

[('perimeter_mean', -0.37636997492008706),
 ('radius_mean', -0.3749259024573016),
 ('radius_worst', -0.3595859180251384),
 ('area_mean', -0.35817591363011586),
 ('perimeter_worst', -0.3535535810462717),
 ('concave_points_worst', -0.3405416297326542),
 ('area_worst', -0.33309683377279126),
 ('concave_points_mean', -0.318120303442199),
 ('concavity_mean', -0.27794916272927545),
 ('compactness_mean', -0.20352376008692796),
 ('area_se', -0.19771041431426892),
 ('concavity_worst', -0.19521571561008402),
 ('lymph_node_status', -0.1524757983253826),
 ('radius_se', -0.1446823819565408),
 ('tumor_size', -0.13009156706246114),
 ('perimeter_se', -0.12068581088326055),
 ('concavity_se', -0.08428719108617608),
 ('compactness_worst', -0.073584730001135),
 ('concave_points_se', -0.046294240186226764),
 ('symmetry_worst', -0.024827328340552096),
 ('symmetry_se', 0.00800770009457895),
 ('texture_mean', 0.014395189972563414),
 ('smoothness_se', 0.034121080120362225),
 ('compactness_se', 0.04252424756549

In [ ]:
lr = make_pipeline(linear_model.LinearRegression())

X=df1[].values
y=df1['time'].values

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=5)

In [ ]:
lr.fit(X_train, y_train)

Pipeline(steps=[('linearregression', LinearRegression())])

In [ ]:
y_pred = lr.predict(X_test)

In [ ]:
# pred_y = y_pred
# for i in range(len(y_pred)):
#   pred_y[i]=(pred_y[i]-min(pred_y))/(max(pred_y)-min(pred_y))

In [ ]:
y_pred

array([-146.46476303,   55.83637676,  -86.8591647 ,  123.378221  ,
        108.39081496,  147.33803053,   79.9216138 ,   88.82164867])

In [ ]:
#print("Accuracy",accuracy_score(y_test, y_pred))
#print("F1_score",f1_score(y_test, y_pred))
#print("Recall",recall_score(y_test, y_pred))

In [ ]:
X_train.shape

(32, 32)

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=5)

In [ ]:
import tensorflow as tf

model1 = tf.keras.models.Sequential()

model1.add(tf.keras.layers.Dense(units = 64, activation = 'tanh', input_shape = (32,)))
model1.add(tf.keras.layers.Dense(units = 32, activation = 'tanh'))
model1.add(tf.keras.layers.Dense(units = 1, activation = 'linear'))
#model1.add(tf.keras.layers.ReLU(threshold=0.5))

model1.compile(optimizer = 'adagrad', loss='mse', metrics=[tf.keras.metrics.MeanAbsoluteError()])

In [ ]:
model1.fit(X_train,y_train, epochs=15, validation_split=0.1)

Epoch 1/15
1/1 [==============================] - 1s 558ms/step - loss: 585.8937 - mean_absolute_error: 18.0698 - val_loss: 2745.1274 - val_mean_absolute_error: 43.4008
Epoch 2/15
1/1 [==============================] - 0s 33ms/step - loss: 576.1349 - mean_absolute_error: 17.7719 - val_loss: 2730.7534 - val_mean_absolute_error: 43.2335
Epoch 3/15
1/1 [==============================] - 0s 52ms/step - loss: 569.4528 - mean_absolute_error: 17.5709 - val_loss: 2716.5562 - val_mean_absolute_error: 43.0602
Epoch 4/15
1/1 [==============================] - 0s 46ms/step - loss: 564.2670 - mean_absolute_error: 17.4248 - val_loss: 2706.5935 - val_mean_absolute_error: 42.9433
Epoch 5/15
1/1 [==============================] - 0s 37ms/step - loss: 560.1763 - mean_absolute_error: 17.3109 - val_loss: 2697.9229 - val_mean_absolute_error: 42.8410
Epoch 6/15
1/1 [==============================] - 0s 32ms/step - loss: 556.6351 - mean_absolute_error: 17.2214 - val_loss: 2690.0540 - val_mean_absolute_error:

In [ ]:
y_pred = model1.predict(X_test)

In [ ]:
y_pred

array([[1.7957217],
       [2.0946302],
       [2.09336  ],
       [2.094639 ],
       [2.0110273],
       [1.5622426],
       [2.35707  ],
       [2.3371167]], dtype=float32)

In [ ]:
y_test

array([ 5, 78, 33, 34, 24, 40, 19,  3])